#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(LGUI(KC_X), LGUI(KC_C), LGUI(KC_V), KC_LSFT, LGUI(KC_Z), LGUI(KC_S), KC_LEFT, LCTL(KC_LALT), KC_RGHT, KC_NO, KC_NO, KC_SPC)
};
